displayName=Gauntlet Coach
author=Conroks
description=Provides post-fight analytics and coaching for the Gauntlet and Corrupted Gauntlet.
tags=gauntlet,corrupted gauntlet,pvm,coach,analytics,post-fight,CG,hunllef,helper,bossing,bosses,ticks,training,teaching,gauntlet coach,gauntlet help,gauntlet helper
plugins=com.gauntletcoach.GauntletCoachPlugin
build=standard